
export interface MPContact {
  constituency: string;
  county: string;
  name: string;
  email: string;
  role: string;
}

export const MP_CONTACTS: MPContact[] = [
  { constituency: "Ainabkoi", county: "Uasin Gishu", name: "Hon. Samuel Chepkonga", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ainamoi", county: "Kericho", name: "Hon. Benjamin Langat", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Aldai", county: "Nandi", name: "Hon. Marianne Jebet Kitany", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Alego Usonga", county: "Siaya", name: "Hon. Samuel Atandi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Awendo", county: "Migori", name: "Hon. John Owino", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bahati", county: "Nakuru", name: "Hon. Irene Mrembo Njoki", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Balambala", county: "Garissa", name: "Hon. Abdi Omar Shurie", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Banissa", county: "Mandera", name: "Hon. Kulow Maalim Hassan", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Baringo Central", county: "Baringo", name: "Hon. Joshua Chepyegon Kandie", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Baringo North", county: "Baringo", name: "Hon. Joseph Kipkoross Makilap", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Baringo South", county: "Baringo", name: "Hon. Charles Kamuren", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Belgut", county: "Kericho", name: "Hon. Nelson Koech", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bobasi", county: "Kisii", name: "Hon. Innocent Obiri", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bomachoge Borabu", county: "Kisii", name: "Hon. Obadiah Barongo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bomachoge Chache", county: "Kisii", name: "Hon. Miruka Ondieki Alfah", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bomet Central", county: "Bomet", name: "Hon. Richard Kilel", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bomet East", county: "Bomet", name: "Hon. Richard Yegon Kipkemoi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bonchari", county: "Kisii", name: "Hon. Charles Mamwacha Onchoke", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bondo", county: "Siaya", name: "Hon. Gideon Ochanda Ogolla", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Borabu", county: "Nyamira", name: "Hon. Patrick Kibagendi Osero", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Budalangi", county: "Busia", name: "Hon. Raphael Bitta Sauti Wanjala", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bumula", county: "Bungoma", name: "Hon. Jack Wamboka", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bura", county: "Tana River", name: "Hon. Yakub Adow", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Bureti", county: "Kericho", name: "Hon. Kibet Kirui Komingoi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Butere", county: "Kakamega", name: "Hon. Nicholas Scott Tindi Mwale", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Butula", county: "Busia", name: "Hon. Joseph Maelo Oyula", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Buuri", county: "Meru", name: "Hon. Mugambi Ridikiri Murwithania", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Central Imenti", county: "Meru", name: "Hon. Moses Nguchine Kirima", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Changamwe", county: "Mombasa", name: "Hon. Omar Mwinyi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Chepalungu", county: "Bomet", name: "Hon. Victor Koech", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Cherangany", county: "Trans Nzoia", name: "Hon. Patrick Simiyu Barasa", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Chesumei", county: "Nandi", name: "Hon. Paul Kibichiy Biego", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Chuka/Igambang''Ombe", county: "Tharaka Nithi", name: "Hon. Patrick Munene Ntwiga", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Dadaab", county: "Garissa", name: "Hon. Farah Maalim", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Dagoretti North", county: "Nairobi", name: "Hon. Beatrice Elachi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Dagoretti South", county: "Nairobi", name: "Hon. John Kiarie Waweru", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Eldama Ravine", county: "Baringo", name: "Hon. Musa Sirma", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Eldas", county: "Wajir", name: "Hon. Adan Keynan Wehliye", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Embakasi Central", county: "Nairobi", name: "Hon. Benjamin Mwangi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Embakasi East", county: "Nairobi", name: "Hon. Babu Owino", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Embakasi North", county: "Nairobi", name: "Hon. James Gakuya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Embakasi South", county: "Nairobi", name: "Hon. Julius Mwathe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Embakasi West", county: "Nairobi", name: "Hon. Mark Mwenje", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Emgwen", county: "Nandi", name: "Hon. Josses Kiptoo Kosgei Lelmengit", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Emuhaya", county: "Vihiga", name: "Hon. Milemba Amboko", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Emurua Dikirr", county: "Narok", name: "Hon. Johana Ngeno Kipyegon", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Endebess", county: "Trans Nzoia", name: "Hon. Robert Pukose", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Fafi", county: "Garissa", name: "Hon. Salah Yakub Farah", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Funyula", county: "Busia", name: "Hon. Wilberforce Oundo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Galole", county: "Tana River", name: "Hon. Said Buya Hiribae", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ganze", county: "Kilifi", name: "Hon. Charo Kenneth Kazungu Tungule", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Garissa Township", county: "Garissa", name: "Hon. Aden Duale", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Garsen", county: "Tana River", name: "Hon. Ali Wario Guyo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Gatanga", county: "Murang'a", name: "Hon. Edward Muriu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Gatundu North", county: "Kiambu", name: "Hon. Elijah Njoroge Kururia", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Gatundu South", county: "Kiambu", name: "Hon. Gabriel Gathuka Kagombe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Gem", county: "Siaya", name: "Hon. Elisha Odhiambo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Gichugu", county: "Kirinyaga", name: "Hon. Robert Gichimu Githinji", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Gilgil", county: "Nakuru", name: "Hon. Martha Wangari Wanjira", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Githunguri", county: "Kiambu", name: "Hon. Gathoni Wamuchomba", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Hamisi", county: "Vihiga", name: "Hon. Charles Gimose", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Homa Bay Town", county: "Homa Bay", name: "Hon. Peter Kaluma", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Igembe Central", county: "Meru", name: "Hon. Dan Kiili Karitho", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Igembe North", county: "Meru", name: "Hon. Julius Taitumu M'anaiba", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Igembe South", county: "Meru", name: "Hon. John Paul Mwirigi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ijara", county: "Garissa", name: "Hon. Abdi Ali Sheikhow", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ikolomani", county: "Kakamega", name: "Hon. Bernard Shinali", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Isiolo North", county: "Isiolo", name: "Hon. Joseph Samal Lomwa", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Isiolo South", county: "Isiolo", name: "Hon. Mohamed Tupi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Jomvu", county: "Mombasa", name: "Hon. Bady Twalib", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Juja", county: "Kiambu", name: "Hon. George Koimburi Ndungu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kabete", county: "Kiambu", name: "Hon. James Githua Kamau Wamacukuru", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kabondo Kasipul", county: "Homa Bay", name: "Hon. Eve Akinyi Obara", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kabuchai", county: "Bungoma", name: "Hon. Joseph Simiyu Wekesa Majimbo Kalasinga", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kacheliba", county: "West Pokot", name: "Hon. Titus Lotee", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kaiti", county: "Makueni", name: "Hon. Joshua Kivinda Kimilu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kajiado Central", county: "Kajiado", name: "Hon. Elijah Memusi Ole Kanchory", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kajiado East", county: "Kajiado", name: "Hon. Kakuta Maimai Hamisi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kajiado North", county: "Kajiado", name: "Hon. Onesmus Ngogoyo Nguro", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kajiado South", county: "Kajiado", name: "Hon. Samuel Parashina Sakimba", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kajiado West", county: "Kajiado", name: "Hon. George Sunkuyia Risa", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kaloleni", county: "Kilifi", name: "Hon. Katana Paul Kahindi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kamukunji", county: "Nairobi", name: "Hon. Yusuf Hassan Abdi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kandara", county: "Murang'a", name: "Hon. Alice Muthoni Wahome", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kanduyi", county: "Bungoma", name: "Hon. John Makali", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kangema", county: "Murang'a", name: "Hon. Peter Irungu Kihungi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kangundo", county: "Machakos", name: "Hon. Fabian Kyule Mule", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kapenguria", county: "West Pokot", name: "Hon. Samwel Moroto Chumel", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kapseret", county: "Uasin Gishu", name: "Hon. Oscar Kipchumba Sudi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Karachuonyo", county: "Homa Bay", name: "Hon. Andrew Adipo Okuome", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kasarani", county: "Nairobi", name: "Hon. Ronald Karauri", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kasipul", county: "Homa Bay", name: "Hon. Vacant", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kathiani", county: "Machakos", name: "Hon. Robert Mbui", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Keiyo North", county: "Elgeyo Marakwet", name: "Hon. Adams Kipsanai Korir", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Keiyo South", county: "Elgeyo Marakwet", name: "Hon. Gideon Kimaiyo Kipkoech", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kesses", county: "Uasin Gishu", name: "Hon. Julius Kipletting Rutto", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Khwisero", county: "Kakamega", name: "Hon. Christopher Aseka Wangaya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kiambaa", county: "Kiambu", name: "Hon. John Njuguna Wanjiku", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kiambu", county: "Kiambu", name: "Hon. John Machua Waithaka", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kibra", county: "Nairobi", name: "Hon. Peter Ochieng Orero", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kibwezi East", county: "Makueni", name: "Hon. Jessica Nduku Kiko Mbalu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kibwezi West", county: "Makueni", name: "Hon. Eckomas Mwengi Mutuse", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kieni", county: "Nyeri", name: "Hon. Antony Njoroge Wainaina", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kigumo", county: "Murang'a", name: "Hon. Joseph Kamau Munyoro", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kiharu", county: "Murang'a", name: "Hon. Samson Ndindi Nyoro", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kikuyu", county: "Kiambu", name: "Hon. Kimani Ichung'wah", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kilgoris", county: "Narok", name: "Hon. Julius Sunkuli", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kilifi North", county: "Kilifi", name: "Hon. Owen Yaa Baya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kilifi South", county: "Kilifi", name: "Hon. Richard Ken Chonga Kiti", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kilome", county: "Makueni", name: "Hon. Thuddeus Kithua Nzambia", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kimilili", county: "Bungoma", name: "Hon. Didmus Wekesa Barasa Mutua", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kiminini", county: "Trans Nzoia", name: "Hon. Maurice Kakai Bisau", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kinango", county: "Kwale", name: "Hon. Samuel Gonzi Rai", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kinangop", county: "Nyandarua", name: "Hon. Zachary Thuku Kwenya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kipipiri", county: "Nyandarua", name: "Hon. Muhia Wanjiku", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kipkelion East", county: "Kericho", name: "Hon. Joseph Kimutai Cherorot", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kipkelion West", county: "Kericho", name: "Hon. Hillary Kiplangat Kosgei", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kirinyaga Central", county: "Kirinyaga", name: "Hon. Gachoki Gitari", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kisauni", county: "Mombasa", name: "Hon. Rashid Juma Bedzimba", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kisumu Central", county: "Kisumu", name: "Hon. Joshua Odongo Oron", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kisumu East", county: "Kisumu", name: "Hon. Shakeel Shabbir", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kisumu West", county: "Kisumu", name: "Hon. Rozaah Akinyi Buyu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitui Central", county: "Kitui", name: "Hon. Makali Benson Mulu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitui East", county: "Kitui", name: "Hon. Nimrod Mbithuka Mbai", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitui Rural", county: "Kitui", name: "Hon. David Mwalika Mboni", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitui South", county: "Kitui", name: "Hon. Rachael Kaki Nyamai", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitui West", county: "Kitui", name: "Hon. Edith Vethi Nyenze", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitutu Chache North", county: "Kisii", name: "Hon. Nyakundi Japheth Mokaya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitutu Chache South", county: "Kisii", name: "Hon. Antoney Kibagendi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kitutu Masaba", county: "Nyamira", name: "Hon. Clive Ombane Gisairo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Konoin", county: "Bomet", name: "Hon. Yegon Brighton Leonard", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kuresoi North", county: "Nakuru", name: "Hon. Alfred Kiprono Mutai", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kuresoi South", county: "Nakuru", name: "Hon. Joseph Kipkosgei Tonui", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kuria East", county: "Migori", name: "Hon. Marwa Kitayama", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kuria West", county: "Migori", name: "Hon. Mathias Robi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Kwanza", county: "Trans Nzoia", name: "Hon. Ferdinand Kevin Wanyonyi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lafey", county: "Mandera", name: "Hon. Mohamed Abdi Abdirahman", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lagdera", county: "Garissa", name: "Hon. Abdikadir Hussein Mohamed", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Laikipia East", county: "Laikipia", name: "Hon. Mwangi Kiunjuri", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Laikipia North", county: "Laikipia", name: "Hon. Sarah Paulata Korere", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Laikipia West", county: "Laikipia", name: "Hon. Wachira Wachira Karani", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Laisamis", county: "Marsabit", name: "Hon. Joseph Lekuton", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lamu East", county: "Lamu", name: "Hon. Ruweida Mohamed Obo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lamu West", county: "Lamu", name: "Hon. Muiruri Muthama Stanley", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Langata", county: "Nairobi", name: "Hon. Phelix Odiwuor Khodhe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lari", county: "Kiambu", name: "Hon. Joseph Mburu Kahangara", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Likoni", county: "Mombasa", name: "Hon. Mishi Juma Khamisi Mboko", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Likuyani", county: "Kakamega", name: "Hon. Innocent Mugabe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Limuru", county: "Kiambu", name: "Hon. John Kiragu Chege", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Loima", county: "Turkana", name: "Hon. Protus Ewesit Akuja", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Luanda", county: "Vihiga", name: "Hon. Dick Maungu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lugari", county: "Kakamega", name: "Hon. Nabii Daraja Nabwera", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lungalunga", county: "Kwale", name: "Hon. Mangale Munga Chiforomodo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Lurambi", county: "Kakamega", name: "Hon. Titus Khamala", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Maara", county: "Tharaka Nithi", name: "Hon. Japhet Miriti Kareke Mbiuki", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Machakos Town", county: "Machakos", name: "Hon. Caleb Mutiso Mule", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Magarini", county: "Kilifi", name: "Hon. Harrison Garama Kombe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Makadara", county: "Nairobi", name: "Hon. George Aladwa", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Makueni", county: "Makueni", name: "Hon. Suzanne Ndunge Kiamba", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Malava", county: "Kakamega", name: "Hon. Moses Malulu Injendi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Malindi", county: "Kilifi", name: "Hon. Amina Laura Mnyazi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mandera East", county: "Mandera", name: "Hon. Husseinweytan Mohamed Abdirahman", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mandera North", county: "Mandera", name: "Hon. Bashir Sheikh Abdullahi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mandera South", county: "Mandera", name: "Hon. Abdul Ebraim Haro", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mandera West", county: "Mandera", name: "Hon. Adan Haji Yussuf", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Manyatta", county: "Embu", name: "Hon. John Gitonga Mwaniki Mukunji", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Maragwa", county: "Murang'a", name: "Hon. Mary Wamaua Waithira Njoroge", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Marakwet East", county: "Elgeyo Marakwet", name: "Hon. David Kangogo Bowen", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Marakwet West", county: "Elgeyo Marakwet", name: "Hon. Timothy Kipchumba Toroitich", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Masinga", county: "Machakos", name: "Hon. Joshua Mbithi Mutua Mwalyo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Matayos", county: "Busia", name: "Hon. Godffrey Odanga", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mathare", county: "Nairobi", name: "Hon. Anthony Oluoch", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mathioya", county: "Murang'a", name: "Hon. Edwin Mugo Gichuki", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mathira", county: "Nyeri", name: "Hon. Eric Mwangi Kahugu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Matuga", county: "Kwale", name: "Hon. Kassim Sawa Tandaza", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Matungu", county: "Kakamega", name: "Hon. Peter Oscar Nabulindo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Matungulu", county: "Machakos", name: "Hon. Stephen Mutinda Mule", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mavoko", county: "Machakos", name: "Hon. Patrick Makau King'ola", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mbeere North", county: "Embu", name: "Hon. Geoffrey Kariuki Kiringa Ruku", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mbeere South", county: "Embu", name: "Hon. Benard Muriuki Nebert", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mbooni", county: "Makueni", name: "Hon. Erastus Kivasu Nzioka", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mogotio", county: "Baringo", name: "Hon. Reuben Kiborek Kipngor", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Moiben", county: "Uasin Gishu", name: "Hon. Phylis Jepkemoi Bartoo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Molo", county: "Nakuru", name: "Hon. Francis Kuria Kimani", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mosop", county: "Nandi", name: "Hon. Abraham Kipsang Kirwa", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Moyale", county: "Marsabit", name: "Hon. Guyo Waqo Jaldesa", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Msambweni", county: "Kwale", name: "Hon. Feisal Abdallah Bader Salim", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mt. Elgon", county: "Bungoma", name: "Hon. Fred Kapondi Chesebe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Muhoroni", county: "Kisumu", name: "Hon. James Onyango Oyoo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mukurweini", county: "Nyeri", name: "Hon. Kaguchia John Philip Gichohi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mumias East", county: "Kakamega", name: "Hon. Peter Kalerwa Salasya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mumias West", county: "Kakamega", name: "Hon. Johnson Manya Naicca", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mvita", county: "Mombasa", name: "Hon. Machele Mohamed Soud", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mwala", county: "Machakos", name: "Hon. Vincent Musyoka Musau", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mwatate", county: "Taita Taveta", name: "Hon. Peter Mbogho Shake", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mwea", county: "Kirinyaga", name: "Hon. Mary Maingi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mwingi Central", county: "Kitui", name: "Hon. Gedion Mutemi Mulyungi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mwingi North", county: "Kitui", name: "Hon. Paul Musyimi Nzengu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Mwingi West", county: "Kitui", name: "Hon. Charles Ngusya Nguna", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Naivasha", county: "Nakuru", name: "Hon. Jayne Wanjiru Njeri Kihara", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nakuru Town East", county: "Nakuru", name: "Hon. David Gikaria", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nakuru Town West", county: "Nakuru", name: "Hon. Samuel Arama", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nambale", county: "Busia", name: "Hon. Geoffey Mulanywa", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nandi Hills", county: "Nandi", name: "Hon. Benard Kibor Kitur", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Narok East", county: "Narok", name: "Hon. Lemanken Aramat", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Narok North", county: "Narok", name: "Hon. Agnes Mantaine Pareyio", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Narok South", county: "Narok", name: "Hon. Kitilai Ole Ntutu", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Narok West", county: "Narok", name: "Hon. Gabriel Koshal Tongoyo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Navakholo", county: "Kakamega", name: "Hon. Emmanuel Wangwe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ndaragwa", county: "Nyandarua", name: "Hon. George N. Gachagua", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ndhiwa", county: "Homa Bay", name: "Hon. Martin Peters Owino", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ndia", county: "Kirinyaga", name: "Hon. George Kariuki", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Njoro", county: "Nakuru", name: "Hon. Charity Kathambi Chepkwony", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "North Horr", county: "Marsabit", name: "Hon. Adhe Wario Guyo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "North Imenti", county: "Meru", name: "Hon. Rahim Dawood Abdul", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "North Mugirango", county: "Nyamira", name: "Hon. Joash Nyamoko", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nyakach", county: "Kisumu", name: "Hon. Joshua Aduma Owuor", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nyali", county: "Mombasa", name: "Hon. Mohammad Ali", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nyando", county: "Kisumu", name: "Hon. Jared Okello Odoyo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nyaribari Chache", county: "Kisii", name: "Hon. Zeheer Jhanda", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nyaribari Masaba", county: "Kisii", name: "Hon. Daniel Ogwoka Manduku", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nyatike", county: "Migori", name: "Hon. Tom Mboya Odege", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Nyeri Town", county: "Nyeri", name: "Hon. Duncan Maina Mathenge", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ol Jorok", county: "Nyandarua", name: "Hon. Michael Muchira", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ol Kalou", county: "Nyandarua", name: "Hon. Njuguna Kiaraho", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Othaya", county: "Nyeri", name: "Hon. Wambugu Wainaina", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Pokot South", county: "West Pokot", name: "Hon. David Pkosing", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Rabai", county: "Kilifi", name: "Hon. Kenga Anthony Mupe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Rangwe", county: "Homa Bay", name: "Hon. Lillian Gogo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Rarieda", county: "Siaya", name: "Hon. Paul Otiende Amollo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Rongai", county: "Nakuru", name: "Hon. Paul Chebor", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Rongo", county: "Migori", name: "Hon. Paul Abuor", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Roysambu", county: "Nairobi", name: "Hon. Augustine Kamande Mwafrika", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ruaraka", county: "Nairobi", name: "Hon. Joseph Tom Kajwang' Francis", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ruiru", county: "Kiambu", name: "Hon. Simon Ng'ang'a Kingara", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Runyenjes", county: "Embu", name: "Hon. Eric Muchangi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Sabatia", county: "Vihiga", name: "Hon. Clement Sloya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Saboti", county: "Trans Nzoia", name: "Hon. Caleb Amisi Luyai", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Saku", county: "Marsabit", name: "Hon. Dido Ali", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Samburu East", county: "Samburu", name: "Hon. Lentoijoni Jackson Lekumontare", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Samburu North", county: "Samburu", name: "Hon. Dominic Eli Letipila", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Samburu West", county: "Samburu", name: "Hon. Naisula Lesuuda", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Seme", county: "Kisumu", name: "Hon. James Nyikal", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Shinyalu", county: "Kakamega", name: "Hon. Fred Akana", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Sigor", county: "West Pokot", name: "Hon. Peter Lochakapong", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Sigowet/Soin", county: "Kericho", name: "Hon. Justice Kipsang Kemei", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Sirisia", county: "Bungoma", name: "Hon. John Waluke Koyi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Sotik", county: "Bomet", name: "Hon. Francis Sigei", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "South Imenti", county: "Meru", name: "Hon. Shadrack Mwiti Ithinji", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "South Mugirango", county: "Kisii", name: "Hon. Sylvanus Osoro", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Soy", county: "Uasin Gishu", name: "Hon. David Kiplagat", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Starehe", county: "Nairobi", name: "Hon. Amos Mwago", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Suba North", county: "Homa Bay", name: "Hon. Millie Odhiambo", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Suba South", county: "Homa Bay", name: "Hon. Caroli Omondi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Subukia", county: "Nakuru", name: "Hon. Samuel Kinuthia Gachobe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Suna East", county: "Migori", name: "Hon. Junet Mohamed", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Suna West", county: "Migori", name: "Hon. Peter Masara", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tarbaj", county: "Wajir", name: "Hon. Hussein Abdi Barre", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Taveta", county: "Taita Taveta", name: "Hon. John Okano Bwire", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Teso North", county: "Busia", name: "Hon. Edward Oku Kaunya", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Teso South", county: "Busia", name: "Hon. Mary Otucho Emaase", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tetu", county: "Nyeri", name: "Hon. Geoffrey Wandeto Mwangi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tharaka", county: "Tharaka Nithi", name: "Hon. George Gitonga Murugara", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Thika Town", county: "Kiambu", name: "Hon. Alice Wambui Ng'ang'a", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tiaty", county: "Baringo", name: "Hon. William Kamket Kassait", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tigania East", county: "Meru", name: "Hon. Lawrence Mpuru Aburi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tigania West", county: "Meru", name: "Hon. John Kanyuithia Mutunga", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tinderet", county: "Nandi", name: "Hon. Julius Kibiwott Meli", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Tongaren", county: "Bungoma", name: "Hon. John Chikati Murumba", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Turbo", county: "Uasin Gishu", name: "Hon. Janet Jepkemboi Sitienei", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Turkana Central", county: "Turkana", name: "Hon. Joseph Namuar Emathe", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Turkana East", county: "Turkana", name: "Hon. Nicholas Ngikor Nixon Ngikolong", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Turkana North", county: "Turkana", name: "Hon. Paul Ekwom Nabuin", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Turkana South", county: "Turkana", name: "Hon. John Ariko Namoit", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Turkana West", county: "Turkana", name: "Hon. Daniel Epuyo Nanok", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ugenya", county: "Siaya", name: "Hon. David Ochieng", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Ugunja", county: "Siaya", name: "Hon. Opiyo Wandayi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Uriri", county: "Migori", name: "Hon. Mark Ogolla Nyamita", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Vihiga", county: "Vihiga", name: "Hon. Ernest Ogesi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Voi", county: "Taita Taveta", name: "Hon. Abdi Chome", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Wajir East", county: "Wajir", name: "Hon. Adan Mohamed Daud", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Wajir North", county: "Wajir", name: "Hon. Ibrahim Abdi Saney", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Wajir South", county: "Wajir", name: "Hon. Mohamed Adow", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Wajir West", county: "Wajir", name: "Hon. Yusuf Farah", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Webuye East", county: "Bungoma", name: "Hon. Martin Manyonyi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Webuye West", county: "Bungoma", name: "Hon. Daniel Wanyama", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "West Mugirango", county: "Nyamira", name: "Hon. Stephen Mogaka", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Westlands", county: "Nairobi", name: "Hon. Tim Wanyonyi", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Wundanyi", county: "Taita Taveta", name: "Hon. Danson Mwashako", email: "info@parliament.go.ke", role: "MP" },
  { constituency: "Yatta", county: "Machakos", name: "Hon. Robert Basil Ngui", email: "info@parliament.go.ke", role: "MP" },
];

export const getMPByConstituency = (constituencyName: string) => {
  const mp = MP_CONTACTS.find(mp => mp.constituency.toLowerCase() === constituencyName.toLowerCase());
  return mp || MP_CONTACTS[MP_CONTACTS.length - 1];
};
