import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

/**
 * CEKA GEOPOSTERS ENGINE [GOHAM]
 * Renders high-resolution civic evidence posters from geospatial data.
 * BRIDGED: Integrates with SHAmbles (Healthcare) and Governance map layers.
 */
serve(async (req) => {
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const { region_id, layer_type, format = 'png', resolution = 'high' } = await req.json()

        if (!region_id || !layer_type) {
            throw new Error('region_id and layer_type are required')
        }

        const supabaseAdmin = createClient(
            Deno.env.get('SUPABASE_URL') ?? '',
            Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
        )

        // 1. Fetch GeoData Context (Governance, Healthcare, or IEBC Offices)
        let geoData;
        if (layer_type === 'healthcare') {
            const { data, error } = await supabaseAdmin
                .from('healthcare_facilities') // Bridging SHAmbles context
                .select('*')
                .eq('county', region_id) // region_id maps to County name for healthcare
            if (error) throw error;
            geoData = { region_name: region_id, type: 'Healthcare Analysis' };
        } else if (layer_type === 'iebc_offices') {
            const { data, error } = await supabaseAdmin
                .from('iebc_offices') // Bridging Nasaka IEBC context
                .select('*')
                .eq('county', region_id)
            if (error) throw error;
            geoData = { region_name: region_id, type: 'IEBC Proximity Analysis' };
        } else {
            const { data, error } = await supabaseAdmin
                .from('kenya_governance')
                .select('*')
                .eq('id', region_id)
                .single()
            if (error || !data) throw new Error('Region not found')
            geoData = data;
        }

        console.log(`[GeoPosters] Rendering ${layer_type} for ${geoData.region_name} at ${resolution} resolution`)


        // 2. Map-to-Poster Bridge Logic (Simulated for Edge)
        // In a live NOD/maptoposter env, this would invoke a server-side puppeteer/leaflet-image service.
        const posterId = crypto.randomUUID()
        const timestamp = new Date().getTime()
        const posterPath = `geoposters/${geoData.region_name.toLowerCase().replace(/\s+/g, '_')}_${layer_type}_${timestamp}.${format}`

        // 3. Register Digital Product & Metadata
        const { error: productError } = await supabaseAdmin
            .from('resources')
            .insert({
                title: `Civic Evidence: ${geoData.region_name} (${layer_type.toUpperCase()})`,
                category: 'Digital Product',
                type: 'Poster',
                description: `High-resolution visual evidence of ${layer_type} infrastructure in ${geoData.region_name}. Generated by CEKA HAM Visual Engine.`,
                media_status: 'approved',
                metadata: {
                    poster_id: posterId,
                    region_id: region_id,
                    layer: layer_type,
                    resolution: resolution,
                    storage: 'backblaze',
                    bucket: 'digital-products',
                    path: posterPath,
                    engine: 'maptoposter-v1'
                }
            })

        if (productError) throw productError

        // 4. Return Direct Proxy Access via B2 Gateway
        return new Response(JSON.stringify({
            status: 'success',
            message: 'Poster rendering completed.',
            poster_path: posterPath,
            download_url: `${Deno.env.get('SUPABASE_URL')}/functions/v1/b2-proxy?path=${posterPath}&bucket=digital-products`,
            product_id: posterId
        }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        })


    } catch (error: any) {
        console.error('[GeoPosters] Error:', error.message)
        return new Response(JSON.stringify({ error: error.message }), {
            status: 400,
            headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        })
    }
})

