-- CEKA Omni-Content Engine: Generated Articles Sync
-- Generated by omni_sync_engine.py

INSERT INTO public.generated_articles (title, excerpt, content, analysis_score, status)
VALUES
('The Public Participation Bill, 2025', 'Neural breakdown of The Public Participation Bill, 2025 through a constitutional lens.', '
        <h1>The Public Participation Bill, 2025: The "Sovereign Citizen" Explainer</h1>
        <p>Listen, my fellow Kenyan. Have you heard about this? They''ve just dropped a new update: <strong>The Public Participation Bill, 2025</strong>.</p>
        <p>In simple terms, this is what''s happening. No big English, just the facts. According to our Constitution (2010), especially Article 10, they <em>must</em> let us speak on this.</p>
        <p><strong>What you need to do:</strong></p>
        <ul>
            <li>Check the raw document here: <a href="https://www.parliament.go.ke/sites/default/files/2025-10/THE%20PUBLIC%20PARTICIPATION%20BILL%2C2025.pdf">https://www.parliament.go.ke/sites/default/files/2025-10/THE%20PUBLIC%20PARTICIPATION%20BILL%2C2025.pdf</a></li>
            <li>Ask your MP what they think about it.</li>
            <li>Don''t sleep on your rights!</li>
        </ul>
        <p><em>Stay hungry, stay civic.</em></p>
        ', 90, 'draft')
ON CONFLICT DO NOTHING;
