import os
import json
import logging
from datetime import datetime
from legislative_scraper import LegislativeScraper

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

class OmniSyncEngine:
    """
    CEKA Omni-Sync Engine: The Grand Orchestrator.
    Bridges Ingestion (Scout), Analysis (Mind), and Generation (Griot).
    """

    def __init__(self, use_mock_ai=True):
        self.use_mock_ai = use_mock_ai
        self.scraper = LegislativeScraper(headless=True)
        self.output_sql = "scripts/generated_articles_sync.sql"

    def run_sync(self):
        logging.info("🚀 Starting Omni-Sync Cycle: Ingestion -> Analysis -> Generation")
        
        # 1. INGESTION (Phase 1)
        scraped_items = self.scraper.scrape_all(max_pages=2) # Limited for sync run
        
        if not scraped_items:
            logging.warning("⚠️ No new items ingested. Sync cycle aborted.")
            return

        generated_count = 0
        sql_rows = []

        # 2 & 3. ANALYSIS & GENERATION (Phase 2 & 3)
        for item in scraped_items:
            # NEURAL JUDGE (Mocked)
            score = self.mock_neural_judge(item)
            
            if score > 50:
                logging.info(f"🧠 Sovereign Mind Approved: {item['title']} (Score: {score})")
                
                # GRIOT GENERATION (Mocked)
                article_content = self.mock_griot_generation(item)
                
                sql_rows.append(self.build_article_sql(item, score, article_content))
                generated_count += 1
            else:
                logging.info(f"🚫 Sovereign Mind Filtered: {item['title']} (Score: {score})")

        if sql_rows:
            self.write_sql_output(sql_rows)
            logging.info(f"✅ Mission Complete: {generated_count} articles generated and staged in {self.output_sql}")
        else:
            logging.info("✅ Mission Complete: No articles met the relevance threshold today.")

    def mock_neural_judge(self, item):
        """Simulates constitutional relevance scoring."""
        text = item['title'].lower()
        score = 20
        if any(kw in text for kw in ['bill', 'act', 'gazette', 'law']): score += 30
        if any(kw in text for kw in ['constitutional', 'participation', 'rights']): score += 40
        return min(score, 100)

    def mock_griot_generation(self, item):
        """Simulates generation using 'Kenyan Voice' templates."""
        title = item['title']
        url = item['url']
        
        return f"""
        <h1>{title}: The "Sovereign Citizen" Explainer</h1>
        <p>Listen, my fellow Kenyan. Have you heard about this? They've just dropped a new update: <strong>{title}</strong>.</p>
        <p>In simple terms, this is what's happening. No big English, just the facts. According to our Constitution (2010), especially Article 10, they <em>must</em> let us speak on this.</p>
        <p><strong>What you need to do:</strong></p>
        <ul>
            <li>Check the raw document here: <a href="{url}">{url}</a></li>
            <li>Ask your MP what they think about it.</li>
            <li>Don't sleep on your rights!</li>
        </ul>
        <p><em>Stay hungry, stay civic.</em></p>
        """

    def build_article_sql(self, item, score, content):
        title = item['title'].replace("'", "''")
        excerpt = f"Neural breakdown of {title} through a constitutional lens.".replace("'", "''")
        content_safe = content.replace("'", "''")
        
        return f"('{title}', '{excerpt}', '{content_safe}', {score}, 'draft')"

    def write_sql_output(self, rows):
        sql_header = """-- CEKA Omni-Content Engine: Generated Articles Sync
-- Generated by omni_sync_engine.py

INSERT INTO public.generated_articles (title, excerpt, content, analysis_score, status)
VALUES
"""
        sql_body = ",\n".join(rows)
        sql_footer = "\nON CONFLICT DO NOTHING;\n"
        
        with open(self.output_sql, 'w', encoding='utf-8') as f:
            f.write(sql_header + sql_body + sql_footer)

if __name__ == "__main__":
    engine = OmniSyncEngine()
    engine.run_sync()
